"""信号塔统一默认值 — scoring_engine 和 web signal_tower 共同引用此模块。"""

# 冷却默认值（秒）
DEFAULT_PRETREND_COOLDOWN = 180
DEFAULT_TREND_COOLDOWN = 120
DEFAULT_TREND_SAME_DIR_BYPASS_SCORE = 0.60
DEFAULT_TREND_SAME_DIR_MID_COOLDOWN = 60
DEFAULT_TREND_REVERSE_COOLDOWN = 300
DEFAULT_FADE_COOLDOWN = 300
DEFAULT_RANGE_COOLDOWN = 300
DEFAULT_NEUTRAL_COOLDOWN = 300

# 阈值默认值
DEFAULT_SCORE_THRESHOLD = 0.50
DEFAULT_PRETREND_THRESHOLD_FLOOR = 0.42
DEFAULT_FADE_THRESHOLD_CEILING = 0.78
DEFAULT_RANGE_THRESHOLD_FLOOR = 0.40
DEFAULT_NEUTRAL_THRESHOLD_OFFSET = 0.10
DEFAULT_TREND_STRONG_ADX_THRESHOLD = 28.0
DEFAULT_TREND_STRONG_THRESHOLD_OFFSET = -0.05

# P1 波动率自适应冷却默认值
DEFAULT_COOLDOWN_VOL_ENABLE = False
DEFAULT_COOLDOWN_VOL_SCALE = 0.0

# P2 时间框架感知冷却倍率
DEFAULT_TF_COOLDOWN_MULTIPLIER_MIN = 0.3
DEFAULT_TF_COOLDOWN_MULTIPLIER_MAX = 3.0
DEFAULT_BAR_SECONDS_M5 = 300  # M5 基准

# ── Market Guard Defaults (Fix #1-#5) ──
DEFAULT_MARKET_CIRCUIT_ATR_MULT = 2.0
DEFAULT_MARKET_RECOVER_ATR_MULT = 1.5
DEFAULT_MARKET_BAR_CONFIRM_ENABLED = True
DEFAULT_MARKET_CIRCUIT_ENABLED = True
DEFAULT_MARKET_AI_GATE_ENABLED = True
DEFAULT_MARKET_AI_GATE_BAR_RANGE_ATR_MULT = 2.0
DEFAULT_MARKET_AI_GATE_BAR_RANGE_AVG_MULT = 10.0
DEFAULT_MARKET_MOMENTUM_THRESHOLD = 2.0
DEFAULT_MARKET_MOMENTUM_WEIGHT = 0.12

# ── Live Bar Redis Key ──
LIVE_BAR_KEY_TEMPLATE = "market:bar:{symbol}:{timeframe}:live"
LIVE_BAR_TTL_SECONDS = 600
